export enum USER_DI_TOKEN {
  USER_CREATE_INBOUND_PORT = 'USER_CREATE_INBOUND_PORT',
  USER_CREATE_OUTBOUND_PORT = 'USER_CREATE_OUTBOUND_PORT',

  USER_GET_INBOUND_PORT = 'USER_GET_INBOUND_PORT',
  USER_GET_OUTBOUND_PORT = 'USER_GET_OUTBOUND_PORT',

  USER_LIST_INBOUND_PORT = 'USER_LIST_INBOUND_PORT',
  USER_LIST_OUTBOUND_PORT = 'USER_LIST_OUTBOUND_PORT',

  USER_UPDATE_INBOUND_PORT = 'USER_UPDATE_INBOUND_PORT',
  USER_UPDATE_OUTBOUND_PORT = 'USER_UPDATE_OUTBOUND_PORT',

  USER_DELETE_INBOUND_PORT = 'USER_DELETE_INBOUND_PORT',
  USER_DELETE_OUTBOUND_PORT = 'USER_DELETE_OUTBOUND_PORT',
}
