version: '3.8'
services:
  mindsai-server:
    build:
      context: . # Dockerfile이 위치한 디렉토리
      dockerfile: Dockerfile
    container_name: mindsai-server
    env_file:
      - src/.env
    ports:
      - '8080:8080'
    restart: always
    networks:
      - my-network

  mysql-db: # 서비스 명
    image: mysql:latest # 사용할 이미지
    restart: always
    container_name: mysql-db # 컨테이너 이름 설정
    networks:
      - my-network
    ports:
      - 3306:3306 # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    volumes:
      - /Users/Shared/data/mysql-db:/var/lib/mysql # 데이터 디렉토리 마운트 설정
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - src/.env

networks:
  my-network:
    driver: bridge
