export enum AUTH_DI_TOKEN {
  AUTH_LOGIN_INBOUND_PORT = 'AUTH_LOGIN_INBOUND_PORT',
  AUTH_REFRESH_INBOUND_PORT = 'AUTH_REFRESH_INBOUND_PORT',
  AUTH_LOGOUT_INBOUND_PORT = 'AUTH_LOGOUT_INBOUND_PORT',
}
